### ISSUE TITLE
Redirect Installer for Post Install Instructions

### ISSUE THREAD

**Issue by jwright** [jwright/sponsorware-bot#1]
Since there are no provisions to allow the app to create a GitHub Sponsors webhook (https://github.com/sponsors/jwright/dashboard/webhooks), we must redirect the installer to instructions so that they can create the webhook manually.

There are provisions to allow for this within the GitHub app setup.

![Screen Shot 2020-08-25 at 9 28 58 AM](https://user-images.githubusercontent.com/35017/91180303-974b8780-e6b5-11ea-9e54-7ee931224af1.png)

The url would have to be able to provide the installer with the webhook url and the webhook secret. These can be placed within environment variables or perhaps pulled from the app programatically (Public Link??). The webhook secret should already be in an environment variable.

Nice to have: Pull out the sponsorship webhook setup urls based on the installation's repositories/github account. This does not seem possible as we would have to identify the installation within the post-install setup url.

**Comment by jwright** [comment]
If we wanted to know more about the installation, the post install endpoint does receive an `installation_id` and `setup_action=install` parameters when the user is redirected.

**Comment by jwright** [comment]
## Tasks

- [x] Add directions for each step
- [x] Set url for current installation?
- [x] ~Add logo~ (future PR)
